# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_auto_20170127_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='no_address', max_length=10),
            preserve_default=False,
        ),
    ]
