# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0003_auto_20170128_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='customer', max_length=10),
        ),
    ]
