# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0004_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('C', 'Customer'), ('O', 'Official')], default='C', max_length=1),
        ),
    ]
