# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0005_auto_20170219_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceno', models.CharField(max_length=10)),
                ('consumption', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
