# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0006_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='timestamp',
            field=models.CharField(max_length=50),
        ),
    ]
